### ISSUE TITLE
Suggest a good name for the website

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#1]
Suggest a good name for the website and update it in the [README.md](https://github.com/ashutoshkrris/paid-technical-writing-opportunities/blob/main/README.md) and the [source](https://github.com/ashutoshkrris/paid-technical-writing-opportunities/blob/main/src/App.vue) file.

**Comment by JoydeepMallick** [comment]
I would like to work on this issue, few suggestions would be :-

1. WriteNPay
2. TechyWrite
3. PaidWriter
4. PocketWriter

BTW if you could elaborate where to include the name in the readme file.

**Comment by ashutoshkrris** [comment]
Hi @JoydeepMallick 
I'd like to go with **TechyWrite**.
You can update this name in the README and source files wherever you find *Paid Writing Opportunities* or *Paid Technical Writing Opportunities*

**Comment by JoydeepMallick** [comment]
OK , I am working on it.
