### ISSUE TITLE
[feature request]: Show a message if no results found

### ISSUE THREAD

**Issue by TsarPrince** [ashutoshkrris/TechyWrite-Old#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

The page looks a bit empty when no data is found for a given user query.
![Screenshot (280)](https://user-images.githubusercontent.com/31801256/196785092-9498013a-fd7b-4747-b7a8-75edb8fc57ad.png)

### Problem/Motivation.

Missing proper message.

### Possible Solution/Pitch.

Dispaly an image with a "no results found" message for such scenarios.

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashutoshkrris** [comment]
Please add a relevant image above the message too.
