### ISSUE TITLE
[feature request]: Add a Back to Top button

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

Add a Back to top button to let users scroll to the top.

### Problem/Motivation.

When scrolling down, users have to manually scroll up which is not good according to UI/UX perspective.

### Possible Solution/Pitch.

Add a back to top button. Ensure that the button is not visible when the user is already on the top of the page. When users scroll down, then the button appears.

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cestaum** [comment]
@ashutoshkrris I would like to work on this.

**Comment by ashutoshkrris** [comment]
Sure @a-u-m 
Go ahead

**Comment by ghost** [comment]
@ashutoshkrris can I work upon this issue? I am a full stack web developer.

**Comment by ashutoshkrris** [comment]
Hi @Igdtuwresource 
@a-u-m is already working on it.
You can look for some other issues in the repository to work on.

**Comment by cestaum** [comment]
Hey @Igdtuwresource You can work on this issue, I haven't actually started it yet. @ashutoshkrris

**Comment by ashutoshkrris** [comment]
@Igdtuwresource Would you like to work on this issue?

**Comment by ghost** [comment]
@ashutoshkrris yeah sure

**Comment by ashutoshkrris** [comment]
Sure, assigning it to you

**Comment by ghost** [comment]
@ashutoshkrris I need to update back to top button in index.html file?
I am new to open source. So please tell

**Comment by FlavioOdas** [comment]
Assign this one to me

**Comment by ashutoshkrris** [comment]
Sure, @FlavioOdas
