### ISSUE TITLE
[Bug]: Categories and Publication overlapping

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

The publication is overlapping with the title of the opportunity.
![Screenshot 2022-10-20 101053](https://user-images.githubusercontent.com/47353498/196858135-03d244b8-e851-452c-bf76-bb92c442fcc0.png)

The categories are also overlapping.
![Screenshot 2022-10-20 101113](https://user-images.githubusercontent.com/47353498/196858176-8416e048-41e3-444f-9536-75039a12ea7e.png)

### Expected Behavior

They should not overlap. It can be similar to below:
![Screenshot 2022-10-20 101625](https://user-images.githubusercontent.com/47353498/196858690-b7ebd70d-1443-40d4-a85b-a66b7bfbaae4.png)

### To Reproduce

Open the website on your mobile and see the bug.

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RachitGarg-12** [comment]
@ashutoshkrris i would like to work on this issue.

**Comment by ashutoshkrris** [comment]
Sure, @RachitGarg-12 
Go ahead

**Comment by ashutoshkrris** [comment]
Hi @RachitGarg-12 
Any update on it?

**Comment by ashutoshkrris** [comment]
Hi @RachitGarg-12 
Let me know if you are still working on this.
If you aren't, I'll unassign you so that others can pick it up.
