### ISSUE TITLE
Create a logo for the website

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#2]
This issue depends on issue #1 
Create a logo on the basis of the suggested name and update it in the project.

**Comment by AnushkaSingh91** [comment]
@ashutoshkrris please assign me this issue.

**Comment by ashutoshkrris** [comment]
Hi @AnushkaSingh91 
Thanks for your interest.
This issue depends on the issue #1. So, you might need to wait for that to be resolved. If you are okay with it, I'll assign the issue to you.

**Comment by AnushkaSingh91** [comment]
@ashutoshkrris I'll surely wait for #1 to get resolved, please assign this issue, it will give a boost to my Hacktoberfest journey.

**Comment by ashutoshkrris** [comment]
Sure @AnushkaSingh91

**Comment by rishabhknowss** [comment]
PLEASE ASSIGJN ME THE TASK

**Comment by rishabhknowss** [comment]
PLEASE ASSIGN ME THE TASK

**Comment by ashutoshkrris** [comment]
Hi @rishabhknowss
@AnushkaSingh91 is already assigned and working on this issue.
You can look for other issues in the repository to work on.

**Comment by AnushkaSingh91** [comment]
@ashutoshkrris I have created the logo according to the given name provided, please select from the following.
And can you please brief me about where to add the final logo.


<img width="500" src="https://user-images.githubusercontent.com/101503258/196664730-d86be95b-d48d-482f-a7c5-ad3a684ee897.png">

<img width="500" src="https://user-images.githubusercontent.com/101503258/196664793-e7e97cb9-e044-4ba0-a3d9-a6f90e5f7981.png">

<img width="500" src="https://user-images.githubusercontent.com/101503258/196664833-b11a3605-c144-4d9c-8ba2-e5b0b6228dd9.png">

**Comment by ashutoshkrris** [comment]
Hi @AnushkaSingh91 
I liked the second one. Make sure you have removed the background.

Create an `image` folder inside the the `public` directory. Add the logo in the `image` folder.
Also make relevant changes on Line 27 in `App.vue` file, as well as add it in the README also.
