### ISSUE TITLE
[feature request]:The SVG fall back image was not implemented in a correct way which makes it hard to work on in the future

### ISSUE THREAD

**Issue by aadi58002** [ashutoshkrris/TechyWrite-Old#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

The #21 PR added the source degign of the svg as a .vue file which was not correct way to use it. 

### Problem/Motivation.

It is hard to understand what is the purpose of the 404.vue file and what it is doing?

### Possible Solution/Pitch.

Save the content into a proper svg file in the public folder and then include it with a img tag.

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashutoshkrris** [comment]
Hi @aadi58002 
Thanks for opening up the issue.
Could you also do the same for other icons in the components folder?

**Comment by aadi58002** [comment]
> Hi @aadi58002 Thanks for opening up the issue. Could you also do the same for other icons in the components folder?

Ok Sure

**Comment by ashutoshkrris** [comment]
Cool, assigning it to you!
