### ISSUE TITLE
[feature request]: Add meta tags

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

Add meta tags to improve the SEO of the page

### Problem/Motivation.

N/A

### Possible Solution/Pitch.

Add the proper meta tags in the index.html file

### Anything else?

This is a beginner friendly issue.

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlavioOdas** [comment]
Assign this to me

**Comment by ashutoshkrris** [comment]
Sure @FlavioOdas
