### ISSUE TITLE
[feature request]: Break the App.vue into different components 

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

As of now, the entire code lies in a single file App.vue which has grown bigger with time.
This can be segregated into different components and put into the components folder.

### Problem/Motivation.

The App.vue file has grown bigger and looks dirty, honestly.

### Possible Solution/Pitch.

This can be segregated into different components and put into the components folder.

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlavioOdas** [comment]
Assign this to me :)

**Comment by ashutoshkrris** [comment]
Sure, @FlavioOdas 
Go ahead
