### ISSUE TITLE
Add categories and publication in the cards

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#3]
The [data.json](https://github.com/ashutoshkrris/paid-technical-writing-opportunities/blob/main/src/data.json) file contains categories and publication for each opportunity. Add them to each card.
You can try to replicate the below style:

![Screenshot 2022-10-19 100510](https://user-images.githubusercontent.com/47353498/196598763-a05816f8-827d-4a98-a857-88422f7d6fba.png)

**Comment by RachitGarg-12** [comment]
@ashutoshkrris i would like to work on this issue.

**Comment by ashutoshkrris** [comment]
Sure @RachitGarg-12 
Go ahead.
