### ISSUE TITLE
[Bug]: Scroll to top button not working

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

There's a bug regarding the Scroll to top button in the mobile version.
When the button overlaps with any card, the button doesn't work. However when the button is between two cards, it works.

### Expected Behavior

It should work even when it overlaps with the cards.

### To Reproduce

* Open the web app in the mobile version
* Scroll down so that the Scroll to top button overlaps with any card
* Click on the button
* See the bug

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlavioOdas** [comment]
Assign this to me

**Comment by ashutoshkrris** [comment]
Sure @FlavioOdas 
Assigning it to you!
