### ISSUE TITLE
[Bug]: Search functionality not working

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

The search functionality is not working on the deployed web app.

### Expected Behavior

It should work and users should be able to search for opportunities.

### To Reproduce

Go to the deployed web app.
Search for anything
See the bug

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alkhimch** [comment]
@ashutoshkrris can you assign to me :)

**Comment by ashutoshkrris** [comment]
Sure @alkhimch 
Go ahead.

**Comment by alkhimch** [comment]
@ashutoshkrris thanks 🙏

**Comment by alkhimch** [comment]
@ashutoshkrris  I can't looking for the bug ? Search func work suddenly working, Can you show detail information of bug ?

**Comment by ashutoshkrris** [comment]
Could you go to https://techywrite.vercel.app/ and try searching for anything?

**Comment by alkhimch** [comment]
Okay its build bug. Now I can handle this. Thanks :)

**Comment by ashutoshkrris** [comment]
Also, the toggle button is not working in the deployed version. Could you also look into that?

**Comment by alkhimch** [comment]
Okay no problem
