### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#4]
Users should be able to search for opportunities using the name and the categories.

**Comment by TsarPrince** [comment]
Hello @ashutoshkrris , I would also love to implement this. May I be assigned?

**Comment by ashutoshkrris** [comment]
Hey @TsarPrince!
Thanks for your interest.
Assigning this to you!

**Comment by TsarPrince** [comment]
Also wanted to add `Ctrl+/` to jump to search bar, but I thought it might be an extra as it's not mentioned in the issue. Let me know what u think of it @ashutoshkrris . Should I create a new issue for that or should I remove it from the PR #11

**Comment by ashutoshkrris** [comment]
Hi @TsarPrince 
You can create a separate issue for that.
