### ISSUE TITLE
[Bug]: Minor bugs in pagination component

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

Currently, the pagination is working fine. But there are a few minor bugs that need to be resolved:

* When the pagination component first loads up, only the Previous and Next buttons are there.
![Screenshot 2022-12-31 005602](https://user-images.githubusercontent.com/47353498/210105704-04047b23-6e80-476a-95b4-8f1eb8752fe3.png)

* Make it responsive (mobile-friendly)
![Screenshot 2022-12-31 005644](https://user-images.githubusercontent.com/47353498/210105723-17f2a99f-7192-4c49-b698-e948a4005eef.png)

### Expected Behavior

The above problems need to be resolved

### To Reproduce

* Go to the deployed web app here: https://techywrite.vercel.app/
* See the problems

### Anything else?

If you see any more bugs related to pagination, do mention it here.

### Hacktoberfest

- [ ] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rishav1707** [comment]
Can I work on mobile responsiveness? @ashutoshkrris

**Comment by ashutoshkrris** [comment]
Yeah sure, @Rishav1707
