### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#6]
As of now, the website shows all of the opportunities on a single page. It would be more user-friendly to have pagination support.

Example:
![Example 1](https://nemecek.be/media/images/django-elided-pagination-example1.png)
![Example 2](https://nemecek.be/media/images/django-elided-pagination-example2.png)
![Example 3](https://nemecek.be/media/images/django-elided-pagination-example3.png)

**Comment by TsarPrince** [comment]
May I be assigned @ashutoshkrris :)

**Comment by ashutoshkrris** [comment]
Hi @TsarPrince 
I have requested some changes in another issue, please look into that.
After that is merged, I'll be more than happy to assign this issue to you.

**Comment by ashutoshkrris** [comment]
@TsarPrince 
If you wish, you can work on this issue now

**Comment by TsarPrince** [comment]
Thanks @ashutoshkrris , running a little busy, I will try to do this one as well later. Till then if anyone else is looking, consider it up for grab.

**Comment by aadi58002** [comment]
Can i take this one ?

**Comment by ashutoshkrris** [comment]
Yeah sure @aadi58002 
Go ahead!

**Comment by aadi58002** [comment]
I created a PR for this issue can you review it?
