### ISSUE TITLE
[feature request]: Add a link to show contributors

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/TechyWrite-Old#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

The website should have a link to show all the contributors have contributed to the repository.

### Problem/Motivation.

Since the project won't have been possible without its contributors, we should give them proper credits.

### Possible Solution/Pitch.

Use the GitHub API to fetch the contributors for the repository.

### Anything else?

Make sure you follow the project's styling.

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TsarPrince** [comment]
I would like to add this, may I be assigned @ashutoshkrris ?

**Comment by ashutoshkrris** [comment]
Sure @TsarPrince 
Go ahead.

**Comment by TsarPrince** [comment]
@ashutoshkrris have a look :)
